accounting/urls.py
from django.contrib import admin
from django.db import router
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "accounting"

urlpatterns = [
    # customers
    path('customers', views.customers, name='customers'),
    path('addcustomer', views.add_customer, name='addcustomer'),
    path('customer/<int:id>', views.customer_detail, name='customer_detail'),
    path('update_customer/<int:id>', views.update_customer, name='update_customer'),
    path('delete_customer/<int:id>', views.delete_customer, name='delete_customer'),

    # bank accounts
    path('bank_accounts', views.bank_accounts, name='bank_accounts'),
    path('bank_account/<int:id>', views.bank_account_detail, name='bank_account_detail'),
    path('add_bank_account', views.add_bank_account, name='add_bank_account'),
    path('update_bank_account/<int:id>', views.update_bank_account, name='update_bank_account'),
    path('delete_bank_account/<int:id>', views.delete_bank_account, name='delete_bank_account'),

    # contracts
    path('contracts', views.contracts, name='contracts'),
    path('contract/<int:id>', views.contract_detail, name='contract_detail'),
    path('add_contract', views.add_contract, name='add_contract'),
    path('set_sales_data', views.set_sales_data, name='ajax_set_sales_data'),
    path('update_contract/<int:id>', views.update_contract, name='update_contract'),
    path('delete_contract/<int:contract_id>', views.delete_contract, name='delete_contract'),

    path('contracts', views.contract_list, name='contract-list'),
    path('contract/<int:id>', views.contractdetail, name='contract-detail'),

    # contract sales
    path('contract_sales', views.contract_sales, name='contract_sales'),
    path('add_contract_sale', views.add_contract_sale, name='add_contract_sale'),
    path('contract_sale_detail/<int:id>', views.contract_sale_detail, name='contract_sale_detail'),
    path('load_contract', views.load_contract, name='ajax_load_contract'),
    path('update_contract_sale/<int:id>', views.update_contract_sale, name='update_contract_sale'),
    path('delete_contract_sale/<int:id>', views.delete_contract_sale, name='delete_contract_sale'),

    path('contractsales_api', views.contractsale_list, name='contractsales-list'),
    path('contractsales_api/<int:id>', views.contractsale_detail, name='contractsale-detail'),

    # contract sales invoice
    path('cont_sale_invoices', views.contract_sale_invoices, name='cont_sale_invoices'),
    path('add_cont_sale_invoice', views.add_contract_sale_invoice, name='add_cont_sale_invoice'),
    path('set_invoice_data', views.set_invoice_data, name='ajax_set_invoice_data'),
    path('cont_sale_invoice_detail/<int:id>', views.cont_sale_invoice_detail, name='cont_sale_invoice_detail'),
    path('update_cont_sale_invoice/<int:id>', views.update_cont_sale_invoice, name='update_cont_sale_invoice'),
    path('delete_cont_sale_invoice/<int:id>', views.delete_cont_sale_invoice, name='delete_cont_sale_invoice'),

    # contract sales transactions
    path('cont_sales_transactions', views.contract_sales_transactions, name='cont_sales_transactions'),
    path('add_cont_sales_transaction', views.add_contract_sales_transaction, name='add_cont_sales_transaction'),
    path('set_transaction_data', views.set_transaction_data, name='ajax_set_transaction_data'),
    path('cont_sales_transaction_detail/<int:id>', views.cont_sales_transaction_detail, name='cont_sales_transaction_detail'),
    path('update_cont_sales_transaction/<int:id>', views.update_cont_sales_transaction, name='update_cont_sales_transaction'),
    path('delete_cont_sales_transaction/<int:id>', views.delete_cont_sales_transaction, name='delete_cont_sales_transaction'),

    # milestones
    path('milestones', views.milestones, name='milestones'),
    path('add_milestone', views.add_milestone, name='add_milestone'),
    # path('milestone_detail/<int:id>', views.milestone_detail, name='milestone_detail'),
    path('update_milestone/<int:id>', views.update_milestone, name='milestone_update'),
    path('delete_milestone/<int:id>', views.delete_milestone, name='delete_milestone'),
    path('set_milestone_data', views.set_milestone_data, name='ajax_set_milestone_data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
import accounting.views
from article import views
from accounting.models import ContractSale


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('article/', include("article.urls")),
    path('user/', include("user.urls")),
    path('accounting/', include("accounting.urls")),
    path('error_404/', accounting.views.error_404, name='error_404')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler403 = 'mysite.views.my_custom_permission_denied_view'
# handler400 = 'mysite.views.my_custom_bad_request_view'
handler404 = "accounting.views.error_404"
# handler500 = "accounting.views.error_500"

accounting/models.py
import datetime

import django
from django.db import models
from django.db.models import Q
from django_cleanup import cleanup
from ckeditor.fields import RichTextField
import django.db.models.options as options
from datetime import date
from django.utils.timezone import now
from django.core.files.storage import FileSystemStorage
from rest_framework import serializers

options.DEFAULT_NAMES = options.DEFAULT_NAMES + (
    'es_index_name', 'es_type_name', 'es_mapping'
)

fs_invoice = FileSystemStorage(location="/invoices")

# Create your models here.


@cleanup.ignore
class Customer(models.Model):
    company = models.CharField(max_length=150, unique=True)
    address = models.CharField(max_length=150)
    web = models.URLField(max_length=150, blank=True, null=True)
    email = models.EmailField(max_length=150, blank=True, null=True)
    responsible = models.CharField(max_length=150, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    company_logo = models.FileField(upload_to='logos/', blank=True, null=True, verbose_name="Add the company logo")
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.company

    class Meta:
        ordering = ['-created_date']
        es_index_name = 'django'
        es_type_name = 'customer'
        es_mapping = {
            'properties': {
                'company': {'type': 'string', 'index': 'not_analyzed'},
                'address': {'type': 'string', 'index': 'not_analyzed'},
                'web': {'type': 'string', 'index': 'not_analyzed'},
                'responsible': {'type': 'string', 'index': 'not_analyzed'},
                'note': {'type': 'string', 'index': 'not_analyzed'}
            }
        }


@cleanup.ignore
class BankAccount(models.Model):
    bank = models.CharField(max_length=150)
    account_alias = models.CharField(max_length=150, unique=True)
    account_type = models.CharField(max_length=50)  # 1: business, 2: personal
    account_no = models.CharField(max_length=150)
    sort_code = models.CharField(max_length=150)
    account_owner = models.CharField(max_length=150)
    currency = models.CharField(verbose_name="currency",  max_length=15)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.account_alias

    class Meta:
        ordering = ['-bank']
        es_index_name = 'django'
        es_type_name = 'bank_account'
        es_mapping = {
            'properties': {
                'bank': {'type': 'string', 'index': 'not_analyzed'},
                'account_alias': {'type': 'string', 'index': 'not_analyzed'},
                'account_type': {'type': 'string', 'index': 'not_analyzed'},
                'account_no': {'type': 'string', 'index': 'not_analyzed'},
                'sort_code': {'type': 'string', 'index': 'not_analyzed'},
                'account_owner': {'type': 'string', 'index': 'not_analyzed'},
                'currency': {'type': 'string', 'index': 'not_analyzed'},
                'note': {'type': 'string', 'index': 'not_analyzed'}
            }
        }


@cleanup.ignore
class Contract(models.Model):
    contract_name = models.CharField(max_length=150, unique=True, blank=True, null=True)
    contract_alias = models.CharField(max_length=100, unique=True)
    customer = models.ForeignKey("accounting.Customer", on_delete=models.CASCADE)
    start_date = models.DateField(help_text='contract start date')
    end_date = models.DateField(help_text='contract end date', blank=True, null=True)
    contract_type = models.ForeignKey("accounting.ContractType", on_delete=models.CASCADE, default=None)
    rate_amount = models.DecimalField(decimal_places=2, max_digits=12)
    currency = models.CharField(max_length=150)         # USD, GBP, etc
    # billing_period = models.CharField(max_length=15)    # weekly, monthly
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.contract_alias

    class Meta:
        ordering = ['-start_date']
        es_index_name = 'django'
        es_type_name = 'contract'
        es_mapping = {
            'properties': {
                'contract_alias': {'type': 'string', 'index': 'not_analyzed'},
                'start_date': {'type': 'date', 'index': 'not_analyzed'},
                'due_date': {'type': 'date', 'index': 'not_analyzed'},
                'rate_type': {'type': 'int', 'index': 'not_analyzed'},
                'rate_amount': {'type': 'float', 'index': 'not_analyzed'},
                'currency': {'type': 'string', 'index': 'not_analyzed'},
                # 'billing_period': {'type': 'string', 'index': 'not_analyzed'},
                'is_active': {'type': 'boolean', 'index': 'not_analyzed'},
                'description': {'type': 'string', 'index': 'not_analyzed'}
            }
        }


@cleanup.ignore
class ContractSale(models.Model):
    contract = models.ForeignKey("accounting.Contract", on_delete=models.CASCADE)
    date = models.DateField(help_text='date', default=django.utils.timezone.now)
    # worked_hours = models.FloatField()
    sales_data = models.JSONField(default=dict)
    total_amount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    is_invoiced = models.BooleanField(default=False)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    # implement calculated field
    # https://stackoverflow.com/questions/44805303/django-model-method-or-calculation-as-field-in-database

    # def total_amount(self):
    #     #  need to dynamically fetched the rate amount on selection change
    #     # in the template form
    #     return self.contract.rate_amount * self.worked_hours
    #
    # def save(self, *args, **kwargs):
    #     self.amount = self.calculate_amount
    #     # self.age = self.get_age
    #     super(ContractSale, self).save(*args, **kwargs)

    def __str__(self):
        return self.contract.contract_alias

    class Meta:
        ordering = ['-date']
        # es_index_name = 'django'
        # es_type_name = 'contract'
        # es_mapping = {
        #     'properties': {
        #         'date': {'type': 'date', 'index': 'not_analyzed'},
        #         'worked_hours': {'type': 'float', 'index': 'not_analyzed'},
        #         'amount': {'type': 'float', 'index': 'not_analyzed'},
        #         'note': {'type': 'string', 'index': 'not_analyzed'}
        #     }
        # }


@cleanup.ignore
class MileStone(models.Model):
    contract = models.ForeignKey("accounting.Contract", on_delete=models.SET_DEFAULT, default=None)
    due_date = models.DateField(help_text='milestone due date', default=now() + datetime.timedelta(days=7))
    delivery_date = models.DateField(help_text='date of delivery', default=now() + datetime.timedelta(days=14))
    milestone_number = models.IntegerField()
    is_completed = models.BooleanField(default=False)
    milestone_amount = models.DecimalField(decimal_places=2, max_digits=6)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, blank=True, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.contract.contract_alias

    class Meta:
        ordering = ['-due_date']
        # es_index_name = 'django'
        # es_type_name = 'contract'
        # es_mapping = {
        #     'properties': {
        #         'contract_alias': {'type': 'string', 'index': 'not_analyzed'},
        #         'start_date': {'type': 'date', 'index': 'not_analyzed'},
        #         'total_amount': {'type': 'float', 'index': 'not_analyzed'},
        #         'milestone_count': {'type': 'integer', 'index': 'not_analyzed'},
        #         'currency': {'type': 'string', 'index': 'not_analyzed'},
        #         'is_active': {'type': 'boolean', 'index': 'not_analyzed'},
        #         'description': {'type': 'string', 'index': 'not_analyzed'}
        #     }
        # }


@cleanup.ignore
class ContractSalesInvoice(models.Model):
    # sales = models.ForeignKey("accounting.ContractSale", on_delete=models.CASCADE, unique=True)
    contract = models.ForeignKey("Contract", on_delete=models.CASCADE, null=True, blank=True, default=None)
    sales_ids = models.CharField(max_length=100, verbose_name="sales_ids")
    invoice_number = models.CharField(max_length=100)
    date = models.DateField(help_text='invoice date', default= django.utils.timezone.now)
    due_date = models.DateField(help_text='invoice due date', default=now() + datetime.timedelta(days=7))
    total_amount = models.DecimalField(verbose_name="total_amount", decimal_places=2, max_digits=12, default=0)
    is_paid_off = models.BooleanField(default=False)
    invoice_file = models.FileField(upload_to='invoices/%Y-%b', blank=True, null=True, verbose_name="Add an invoice file")
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.invoice_number

    class Meta:
        ordering = ['-due_date']


@cleanup.ignore
class ContractSalesTransaction(models.Model):
    invoice = models.ForeignKey("accounting.ContractSalesInvoice", on_delete=models.CASCADE)
    date = models.DateField(help_text='invoice date', default=django.utils.timezone.now)
    amount = models.DecimalField(max_digits=12, decimal_places=2)

templates/accounting/contract_sales_invoice/add_cont_sale_invoice.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
    <div class="col-md-6 offset-md-3" style = "margin-top:20px;">
        <h3>Add Contract Sale Invoice - {{ invoice_data.id }} </h3>
        <hr>
        <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-primary">Add Contract Sale Invoice</button>
        </form>
    </div>
    </div>
        {% for idata in invoice_data %}

        {% endfor %}


    <script>
        let total_amount = 0;

        document.addEventListener("DOMContentLoaded", function(event) {
            let invoice_data = {{ invoice_data|safe }};
            const sales_ids = [];
            var total = 0;

            console.log(invoice_data);
            if (invoice_data) {
                for (var i=0; i<invoice_data.length; i++){
                    total += parseFloat(invoice_data[i].total_amount);
                    sales_ids.push(invoice_data[i].id);
                }
                console.log("sales_id:" + sales_ids );
                console.log("total:" + total );

                set_fields("id_sales_ids", sales_ids);
                set_fields("id_contract", invoice_data[0].contract__id);
                set_fields("id_total_amount", total);

            }else{
                console.log("invoice data not received!");
            }


        });

        function get_total_amount(total){
            total_amount += total;
            console.log("total amount: " + total_amount);
        }

        function set_fields(el_name, new_value){
            console.log("setting selected values for " + el_name);
            var el = document.getElementById(el_name);
            $(el).val(new_value);
        }

        document.getElementById("id_invoice_file").addEventListener("change",function(){
            var filename = this.value
            if (filename){
                filename = filename.replace(/^.*[\\\/]/, '').replace('.pdf','');
                console.log("filename: " + filename);
                set_fields("id_invoice_number", filename);
            }
            console.log("file selected:" + filename);
        })
    </script>


{% endblock body %}
{% load static %}


templates/accounting/contract_sales_invoice/cont_sale_invoice_detail.html
{% extends "layout.html" %}

{% block body %}
    
  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8 p-3 mb-2 bg-light text-dark">

        <!-- Contract Alias -->
        <h4 class="mt-4">Invoice Details</h4>
        <hr>
        <!-- Post Content -->
        <p class="lead">
            <b>Contract:</b> {{ cont_sale_invoice.contract__contract_alias|safe }}
        </p>
        <p class="lead">
            <b>Invoice Number:</b> {{ cont_sale_invoice.invoice_number|safe }}
        </p>
        <p class="lead">
            <b>Date:</b> {{ cont_sale_invoice.date|safe }}
        </p>
        <p class="lead">
            <b>Due Date:</b> {{ cont_sale_invoice.due_date|safe }}
        </p>
        <p class="lead">
            <b>Currency:</b> {{ cont_sale_invoice.contract__currency|safe }}
        </p>
        <p class="lead">
            <b>Total Amount:</b> {{ cont_sale_invoice.total_amount|safe }}
        </p>
        <p class="lead">
            <b>Is Paid off:</b> {{ cont_sale_invoice.is_paid_off|safe }}
        </p>
        <p class="lead">
            <b>Invoice File:</b> {{ cont_sale_invoice.invoice_file|safe }}
        </p>
        <p class="lead">
            <b>Note:</b> {{ cont_sale_invoice.note|safe }}
        </p>


    </div> <!--post content form-->
    
  </div>  <!-- /.row -->

        <a href="{% url 'accounting:cont_sale_invoices' %}">Return</a>
{% endblock body %}

templates/accounting/contract_sales_invoice/cont_sale_invoice_update.html
{% extends "layout.html" %}
cont_sale_invoice_update.html
{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
    <div class="col-md-6 offset-md-3" style = "margin-top:20px;">
        <h3>Update Contract Sale Invoice</h3>
        <hr>
        <form method = "POST">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>

    </div>
    </div>
{% endblock body %}

templates/accounting/contract_sales_invoice/cont_sale_invoices.html
{% extends "layout.html" %}
{% load humanize %}
{% load mathfilters %}
{% block body %}
    


    <div class="container-fluid">
<!--     <a class="btn btn-primary disabled" href ="{% url 'accounting:add_cont_sale_invoice' %}">Add Contract Sale Invoice</a>-->
        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <form>
                  <h3>Contract Sales Invoices</h3>
                  <p>&nbsp;</p>
                  <a class="btn btn-primary btn-md disabled"  id="id_btn_payoff" onclick="set_transaction_data()">Pay off</a>
<!--                {% csrf_token %}-->
<!--                <button class="btn btn-secondary" type="submit">Search</button>-->
          </div>
<!--                <input type="text" name="keyword" class="form-control" placeholder="Input a keyword to search for ..." aria-label="" aria-describedby="basic-addon1">-->
              </form>
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <form>
                {% csrf_token %}
                <button class="btn btn-secondary" type="submit">Search</button>
          </div>
                <input type="text" name="keyword" class="form-control" placeholder="Input a keyword ..." aria-label="" aria-describedby="basic-addon1">
              </form>
        </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1" checked />
                <label class="form-check-label" for="inlineCheckbox1">Hide paid off</label>
            </div>

    {% if not cont_sales_invoices %}
        <div class="alert alert-danger" style = "margin-top:20px;">There is no contract sale invoice yet.</div>

    {% else %}
        <table class="table table-hover" style="margin-top:20px;">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">payoff</th>
                    <th scope="col">Invoice Number</th>
                    <th scope="col">Contract Alias</th>
                    <th scope="col">Date</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Total Amount</th>
                    <th scope="col">Paid off</th>
                    <th scope="col">Currency</th>
                </tr>
            </thead>
            <tbody>
                {% for cs in cont_sales_invoices  %}
                    <tr>
                        <th scope="row">{{ cs.id }}</th>
                        {% if cs.is_paid_off %}
                        <td><input class="form-check-input" type="radio" name="radio-select-topay" style="vertical-align: middle; margin: 10px;" disabled></td>
                        {% else %}
                        <td><input class="form-check-input radioPayoff" style="vertical-align: middle; margin: 10px;" name="radio-payoff" type="radio" value="{{ cs.id }}"></td>
                        {% endif %}
                        <td><a title="Invoice details" href="{% url 'accounting:cont_sale_invoice_detail' cs.id %}#container">{{ cs.invoice_number }}</a></td>
                        <td><a title="Contract details" href="{% url 'accounting:contract_detail' cs.contract__id %}#container">{{ cs.contract__contract_alias }}</a></td>
                        <td>{{ cs.date }}</td>
                        <td>{{ cs.due_date }}</td>
                        <td>{{ cs.total_amount }}</td>
                        <td>{{ cs.is_paid_off }}</td>
                        <td>{{ cs.contract__currency }}</td>
                        <td><a href="{% url 'accounting:update_cont_sale_invoice' cs.id %}">Update</a></td>
                        <td><a class="confirm-delete" href="{% url 'accounting:delete_cont_sale_invoice' cs.id %}">Delete</a></td>
                    </tr>
                {% endfor %}

            </tbody>
            </div>
        </table>
    <script>

    let invoice_id = 0;
    $(document).on('click', '.confirm-delete', function(){
        return confirm('Are you sure you want to delete this?');
    })

    function getElement(elm){
        return document.getElementById(elm);
    }

    function removeClass(elm, class_name){
        var stat = elm.classList.contains("disabled");
        if (stat == true) {
            elm.classList.remove(class_name);
            console.log("class name removed:" + class_name);
        }
    }

    function addClass(elm, class_name){
        var stat = elm.classList.contains(class_name);
        if (stat == false) {
            elm.classList.add(class_name);
            console.log("class name removed:" + class_name);
        }
    }

    var matches = document.querySelectorAll('.radioPayoff');
    for (match in matches) {
      matches[match].onclick = function() {
        invoice_id = this.value;
        console.log("invoice id set!");
        var btn_payoff = getElement('id_btn_payoff');
        removeClass(btn_payoff, "disabled");
        removeClass(btn_payoff, "text-gray");
        addClass(btn_payoff, "text-white");
      }
    }

    function set_transaction_data(){
        console.log("hello!");
        const url = "/accounting/set_transaction_data";  // get the url of the view
        console.log("url: "+url);
        console.log("invoice id: " +invoice_id);
        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/accounting/load-contract/)
          dataType: "json",
          method: "POST",
          data: {
            'csrfmiddlewaretoken': '{{ csrf_token }}',
            'invoice_id': invoice_id,       // add the contract id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_contracts` view function
            console.log(data.invoice_number);
            window.location.href = "{% url 'accounting:add_cont_sales_transaction' %}"
    <!--        $("#id_rate_amount").html(data.rate_amount);-->
    <!--        $("#id_rate_amount").val(data.rate_amount);-->
          },
            error: function(e)
            {
                console.log('Error: ' + e);
            }
        });
  }

    </script>
        
    {% endif %}
{% endblock body %}