accounting/urls.py
from django.contrib import admin
from django.db import router
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "accounting"

urlpatterns = [
    # customers
    path('customers', views.customers, name='customers'),
    path('addcustomer', views.add_customer, name='addcustomer'),
    path('customer/<int:id>', views.customer_detail, name='customer_detail'),
    path('update_customer/<int:id>', views.update_customer, name='update_customer'),
    path('delete_customer/<int:id>', views.delete_customer, name='delete_customer'),

    # bank accounts
    path('bank_accounts', views.bank_accounts, name='bank_accounts'),
    path('bank_account/<int:id>', views.bank_account_detail, name='bank_account_detail'),
    path('add_bank_account', views.add_bank_account, name='add_bank_account'),
    path('update_bank_account/<int:id>', views.update_bank_account, name='update_bank_account'),
    path('delete_bank_account/<int:id>', views.delete_bank_account, name='delete_bank_account'),

    # contracts
    path('contracts', views.contracts, name='contracts'),
    path('contract/<int:id>', views.contract_detail, name='contract_detail'),
    path('add_contract', views.add_contract, name='add_contract'),
    path('set_sales_data', views.set_sales_data, name='ajax_set_sales_data'),
    path('update_contract/<int:id>', views.update_contract, name='update_contract'),
    path('delete_contract/<int:contract_id>', views.delete_contract, name='delete_contract'),

    path('contracts', views.contract_list, name='contract-list'),
    path('contract/<int:id>', views.contractdetail, name='contract-detail'),

    # contract sales
    path('contract_sales', views.contract_sales, name='contract_sales'),
    path('add_contract_sale', views.add_contract_sale, name='add_contract_sale'),
    path('contract_sale_detail/<int:id>', views.contract_sale_detail, name='contract_sale_detail'),
    path('load_contract', views.load_contract, name='ajax_load_contract'),
    path('update_contract_sale/<int:id>', views.update_contract_sale, name='update_contract_sale'),
    path('delete_contract_sale/<int:id>', views.delete_contract_sale, name='delete_contract_sale'),

    path('contractsales_api', views.contractsale_list, name='contractsales-list'),
    path('contractsales_api/<int:id>', views.contractsale_detail, name='contractsale-detail'),

    # contract sales invoice
    path('cont_sale_invoices', views.contract_sale_invoices, name='cont_sale_invoices'),
    path('add_cont_sale_invoice', views.add_contract_sale_invoice, name='add_cont_sale_invoice'),
    path('set_invoice_data', views.set_invoice_data, name='ajax_set_invoice_data'),
    path('cont_sale_invoice_detail/<int:id>', views.cont_sale_invoice_detail, name='cont_sale_invoice_detail'),
    path('update_cont_sale_invoice/<int:id>', views.update_cont_sale_invoice, name='update_cont_sale_invoice'),
    path('delete_cont_sale_invoice/<int:id>', views.delete_cont_sale_invoice, name='delete_cont_sale_invoice'),

    # contract sales transactions
    path('cont_sales_transactions', views.contract_sales_transactions, name='cont_sales_transactions'),
    path('add_cont_sales_transaction', views.add_contract_sales_transaction, name='add_cont_sales_transaction'),
    path('set_transaction_data', views.set_transaction_data, name='ajax_set_transaction_data'),
    path('cont_sales_transaction_detail/<int:id>', views.cont_sales_transaction_detail, name='cont_sales_transaction_detail'),
    path('update_cont_sales_transaction/<int:id>', views.update_cont_sales_transaction, name='update_cont_sales_transaction'),
    path('delete_cont_sales_transaction/<int:id>', views.delete_cont_sales_transaction, name='delete_cont_sales_transaction'),

    # milestones
    path('milestones', views.milestones, name='milestones'),
    path('add_milestone', views.add_milestone, name='add_milestone'),
    # path('milestone_detail/<int:id>', views.milestone_detail, name='milestone_detail'),
    path('update_milestone/<int:id>', views.update_milestone, name='milestone_update'),
    path('delete_milestone/<int:id>', views.delete_milestone, name='delete_milestone'),
    path('set_milestone_data', views.set_milestone_data, name='ajax_set_milestone_data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard', views.dashboard, name="dashboard"),
    path('addarticle', views.addArticle, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.articleUpdate, name="update"),
    path('delete/<int:id>', views.deleteArticle, name='delete'),
    # path('', views.articles, name='articles'),
    path('comment/<int:id>', views.addComment, name='comment')
]



blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
import accounting.views
from article import views
from accounting.models import ContractSale


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('article/', include("article.urls")),
    path('user/', include("user.urls")),
    path('accounting/', include("accounting.urls")),
    path('error_404/', accounting.views.error_404, name='error_404')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler403 = 'mysite.views.my_custom_permission_denied_view'
# handler400 = 'mysite.views.my_custom_bad_request_view'
handler404 = "accounting.views.error_404"
# handler500 = "accounting.views.error_500"

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

templates/includes/footer.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>

    </head>
    <body>
        <div class="card text-center">
              <div class="card-body">
                <h5 class="card-title">TSmart Personal Assistant</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <!--    <a href="#" class="btn btn-primary">Go somewhere</a>-->
              </div>
        </div>
    </body>
</html>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{% url 'index' %}">TS Base</a>
          <ul class="navbar-nav mr-auto">

            <li class="nav-item">
              <a class="nav-link" href="{% url 'article:dashboard' %}">Articles</a>
            </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Accounting
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'accounting:customers' %}">Customers</a>
                  <a class="dropdown-item" href="{% url 'accounting:bank_accounts' %}">Bank Accounts</a>

                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'accounting:contracts' %}">1. Contracts</a>
                  <a class="dropdown-item" href="{% url 'accounting:contract_sales' %}">2. Contract Sales</a>
                  <a class="dropdown-item" href="{% url 'accounting:cont_sale_invoices' %}">3. Contract Sales Invoices</a>
                  <a class="dropdown-item" href="{% url 'accounting:cont_sales_transactions' %}">4. Contract Sales Transactions</a>

                </div>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>

          </ul>

          <ul class="navbar-nav ml-auto">

            {% if request.user.is_authenticated %}
              <li class="nav-item">
                   <a class="nav-link" href="{% url 'user:logout' %}">Logout [{{ request.user.username }}]</a>
              </li>
            {% else %}
              <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                  </li>
            {% endif %}
                 <li class="nav-item">
                <a class="nav-link" href="{% url 'user:register' %}">Register</a>
              </li>
          </ul>
        </div>
      </nav>

templates/includes/posttemplate.html
 <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>