accounting/urls.py
from django.contrib import admin
from django.db import router
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "accounting"

urlpatterns = [
    # customers
    path('customers', views.customers, name='customers'),
    path('addcustomer', views.add_customer, name='addcustomer'),
    path('customer/<int:id>', views.customer_detail, name='customer_detail'),
    path('update_customer/<int:id>', views.update_customer, name='update_customer'),
    path('delete_customer/<int:id>', views.delete_customer, name='delete_customer'),

    # bank accounts
    path('bank_accounts', views.bank_accounts, name='bank_accounts'),
    path('bank_account/<int:id>', views.bank_account_detail, name='bank_account_detail'),
    path('add_bank_account', views.add_bank_account, name='add_bank_account'),
    path('update_bank_account/<int:id>', views.update_bank_account, name='update_bank_account'),
    path('delete_bank_account/<int:id>', views.delete_bank_account, name='delete_bank_account'),

    # contracts
    path('contracts', views.contracts, name='contracts'),
    path('contract/<int:id>', views.contract_detail, name='contract_detail'),
    path('add_contract', views.add_contract, name='add_contract'),
    path('set_sales_data', views.set_sales_data, name='ajax_set_sales_data'),
    path('update_contract/<int:id>', views.update_contract, name='update_contract'),
    path('delete_contract/<int:contract_id>', views.delete_contract, name='delete_contract'),

    path('contracts', views.contract_list, name='contract-list'),
    path('contract/<int:id>', views.contractdetail, name='contract-detail'),

    # contract sales
    path('contract_sales', views.contract_sales, name='contract_sales'),
    path('add_contract_sale', views.add_contract_sale, name='add_contract_sale'),
    path('contract_sale_detail/<int:id>', views.contract_sale_detail, name='contract_sale_detail'),
    path('load_contract', views.load_contract, name='ajax_load_contract'),
    path('update_contract_sale/<int:id>', views.update_contract_sale, name='update_contract_sale'),
    path('delete_contract_sale/<int:id>', views.delete_contract_sale, name='delete_contract_sale'),

    path('contractsales_api', views.contractsale_list, name='contractsales-list'),
    path('contractsales_api/<int:id>', views.contractsale_detail, name='contractsale-detail'),

    # contract sales invoice
    path('cont_sale_invoices', views.contract_sale_invoices, name='cont_sale_invoices'),
    path('add_cont_sale_invoice', views.add_contract_sale_invoice, name='add_cont_sale_invoice'),
    path('set_invoice_data', views.set_invoice_data, name='ajax_set_invoice_data'),
    path('cont_sale_invoice_detail/<int:id>', views.cont_sale_invoice_detail, name='cont_sale_invoice_detail'),
    path('update_cont_sale_invoice/<int:id>', views.update_cont_sale_invoice, name='update_cont_sale_invoice'),
    path('delete_cont_sale_invoice/<int:id>', views.delete_cont_sale_invoice, name='delete_cont_sale_invoice'),

    # contract sales transactions
    path('cont_sales_transactions', views.contract_sales_transactions, name='cont_sales_transactions'),
    path('add_cont_sales_transaction', views.add_contract_sales_transaction, name='add_cont_sales_transaction'),
    path('set_transaction_data', views.set_transaction_data, name='ajax_set_transaction_data'),
    path('cont_sales_transaction_detail/<int:id>', views.cont_sales_transaction_detail, name='cont_sales_transaction_detail'),
    path('update_cont_sales_transaction/<int:id>', views.update_cont_sales_transaction, name='update_cont_sales_transaction'),
    path('delete_cont_sales_transaction/<int:id>', views.delete_cont_sales_transaction, name='delete_cont_sales_transaction'),

    # milestones
    path('milestones', views.milestones, name='milestones'),
    path('add_milestone', views.add_milestone, name='add_milestone'),
    # path('milestone_detail/<int:id>', views.milestone_detail, name='milestone_detail'),
    path('update_milestone/<int:id>', views.update_milestone, name='milestone_update'),
    path('delete_milestone/<int:id>', views.delete_milestone, name='delete_milestone'),
    path('set_milestone_data', views.set_milestone_data, name='ajax_set_milestone_data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
import accounting.views
from article import views
from accounting.models import ContractSale


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('article/', include("article.urls")),
    path('user/', include("user.urls")),
    path('accounting/', include("accounting.urls")),
    path('error_404/', accounting.views.error_404, name='error_404')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler403 = 'mysite.views.my_custom_permission_denied_view'
# handler400 = 'mysite.views.my_custom_bad_request_view'
handler404 = "accounting.views.error_404"
# handler500 = "accounting.views.error_500"

accounting/models.py
import datetime

import django
from django.db import models
from django.db.models import Q
from django_cleanup import cleanup
from ckeditor.fields import RichTextField
import django.db.models.options as options
from datetime import date
from django.utils.timezone import now
from django.core.files.storage import FileSystemStorage
from rest_framework import serializers

options.DEFAULT_NAMES = options.DEFAULT_NAMES + (
    'es_index_name', 'es_type_name', 'es_mapping'
)

fs_invoice = FileSystemStorage(location="/invoices")

# Create your models here.


@cleanup.ignore
class Customer(models.Model):
    company = models.CharField(max_length=150, unique=True)
    address = models.CharField(max_length=150)
    web = models.URLField(max_length=150, blank=True, null=True)
    email = models.EmailField(max_length=150, blank=True, null=True)
    responsible = models.CharField(max_length=150, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    company_logo = models.FileField(upload_to='logos/', blank=True, null=True, verbose_name="Add the company logo")
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.company

    class Meta:
        ordering = ['-created_date']
        es_index_name = 'django'
        es_type_name = 'customer'
        es_mapping = {
            'properties': {
                'company': {'type': 'string', 'index': 'not_analyzed'},
                'address': {'type': 'string', 'index': 'not_analyzed'},
                'web': {'type': 'string', 'index': 'not_analyzed'},
                'responsible': {'type': 'string', 'index': 'not_analyzed'},
                'note': {'type': 'string', 'index': 'not_analyzed'}
            }
        }


@cleanup.ignore
class BankAccount(models.Model):
    bank = models.CharField(max_length=150)
    account_alias = models.CharField(max_length=150, unique=True)
    account_type = models.CharField(max_length=50)  # 1: business, 2: personal
    account_no = models.CharField(max_length=150)
    sort_code = models.CharField(max_length=150)
    account_owner = models.CharField(max_length=150)
    currency = models.CharField(verbose_name="currency",  max_length=15)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.account_alias

    class Meta:
        ordering = ['-bank']
        es_index_name = 'django'
        es_type_name = 'bank_account'
        es_mapping = {
            'properties': {
                'bank': {'type': 'string', 'index': 'not_analyzed'},
                'account_alias': {'type': 'string', 'index': 'not_analyzed'},
                'account_type': {'type': 'string', 'index': 'not_analyzed'},
                'account_no': {'type': 'string', 'index': 'not_analyzed'},
                'sort_code': {'type': 'string', 'index': 'not_analyzed'},
                'account_owner': {'type': 'string', 'index': 'not_analyzed'},
                'currency': {'type': 'string', 'index': 'not_analyzed'},
                'note': {'type': 'string', 'index': 'not_analyzed'}
            }
        }


@cleanup.ignore
class Contract(models.Model):
    contract_name = models.CharField(max_length=150, unique=True, blank=True, null=True)
    contract_alias = models.CharField(max_length=100, unique=True)
    customer = models.ForeignKey("accounting.Customer", on_delete=models.CASCADE)
    start_date = models.DateField(help_text='contract start date')
    end_date = models.DateField(help_text='contract end date', blank=True, null=True)
    contract_type = models.ForeignKey("accounting.ContractType", on_delete=models.CASCADE, default=None)
    rate_amount = models.DecimalField(decimal_places=2, max_digits=12)
    currency = models.CharField(max_length=150)         # USD, GBP, etc
    # billing_period = models.CharField(max_length=15)    # weekly, monthly
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.contract_alias

    class Meta:
        ordering = ['-start_date']
        es_index_name = 'django'
        es_type_name = 'contract'
        es_mapping = {
            'properties': {
                'contract_alias': {'type': 'string', 'index': 'not_analyzed'},
                'start_date': {'type': 'date', 'index': 'not_analyzed'},
                'due_date': {'type': 'date', 'index': 'not_analyzed'},
                'rate_type': {'type': 'int', 'index': 'not_analyzed'},
                'rate_amount': {'type': 'float', 'index': 'not_analyzed'},
                'currency': {'type': 'string', 'index': 'not_analyzed'},
                # 'billing_period': {'type': 'string', 'index': 'not_analyzed'},
                'is_active': {'type': 'boolean', 'index': 'not_analyzed'},
                'description': {'type': 'string', 'index': 'not_analyzed'}
            }
        }


@cleanup.ignore
class ContractSale(models.Model):
    contract = models.ForeignKey("accounting.Contract", on_delete=models.CASCADE)
    date = models.DateField(help_text='date', default=django.utils.timezone.now)
    # worked_hours = models.FloatField()
    sales_data = models.JSONField(default=dict)
    total_amount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    is_invoiced = models.BooleanField(default=False)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    # implement calculated field
    # https://stackoverflow.com/questions/44805303/django-model-method-or-calculation-as-field-in-database

    # def total_amount(self):
    #     #  need to dynamically fetched the rate amount on selection change
    #     # in the template form
    #     return self.contract.rate_amount * self.worked_hours
    #
    # def save(self, *args, **kwargs):
    #     self.amount = self.calculate_amount
    #     # self.age = self.get_age
    #     super(ContractSale, self).save(*args, **kwargs)

    def __str__(self):
        return self.contract.contract_alias

    class Meta:
        ordering = ['-date']
        # es_index_name = 'django'
        # es_type_name = 'contract'
        # es_mapping = {
        #     'properties': {
        #         'date': {'type': 'date', 'index': 'not_analyzed'},
        #         'worked_hours': {'type': 'float', 'index': 'not_analyzed'},
        #         'amount': {'type': 'float', 'index': 'not_analyzed'},
        #         'note': {'type': 'string', 'index': 'not_analyzed'}
        #     }
        # }


@cleanup.ignore
class MileStone(models.Model):
    contract = models.ForeignKey("accounting.Contract", on_delete=models.SET_DEFAULT, default=None)
    due_date = models.DateField(help_text='milestone due date', default=now() + datetime.timedelta(days=7))
    delivery_date = models.DateField(help_text='date of delivery', default=now() + datetime.timedelta(days=14))
    milestone_number = models.IntegerField()
    is_completed = models.BooleanField(default=False)
    milestone_amount = models.DecimalField(decimal_places=2, max_digits=6)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, blank=True, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.contract.contract_alias

    class Meta:
        ordering = ['-due_date']
        # es_index_name = 'django'
        # es_type_name = 'contract'
        # es_mapping = {
        #     'properties': {
        #         'contract_alias': {'type': 'string', 'index': 'not_analyzed'},
        #         'start_date': {'type': 'date', 'index': 'not_analyzed'},
        #         'total_amount': {'type': 'float', 'index': 'not_analyzed'},
        #         'milestone_count': {'type': 'integer', 'index': 'not_analyzed'},
        #         'currency': {'type': 'string', 'index': 'not_analyzed'},
        #         'is_active': {'type': 'boolean', 'index': 'not_analyzed'},
        #         'description': {'type': 'string', 'index': 'not_analyzed'}
        #     }
        # }


@cleanup.ignore
class ContractSalesInvoice(models.Model):
    # sales = models.ForeignKey("accounting.ContractSale", on_delete=models.CASCADE, unique=True)
    contract = models.ForeignKey("Contract", on_delete=models.CASCADE, null=True, blank=True, default=None)
    sales_ids = models.CharField(max_length=100, verbose_name="sales_ids")
    invoice_number = models.CharField(max_length=100)
    date = models.DateField(help_text='invoice date', default= django.utils.timezone.now)
    due_date = models.DateField(help_text='invoice due date', default=now() + datetime.timedelta(days=7))
    total_amount = models.DecimalField(verbose_name="total_amount", decimal_places=2, max_digits=12, default=0)
    is_paid_off = models.BooleanField(default=False)
    invoice_file = models.FileField(upload_to='invoices/%Y-%b', blank=True, null=True, verbose_name="Add an invoice file")
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=None, null=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.invoice_number

    class Meta:
        ordering = ['-due_date']


@cleanup.ignore
class ContractSalesTransaction(models.Model):
    invoice = models.ForeignKey("accounting.ContractSalesInvoice", on_delete=models.CASCADE)
    date = models.DateField(help_text='invoice date', default=django.utils.timezone.now)
    amount = models.DecimalField(max_digits=12, decimal_places=2)

templates/accounting/contract_sale/contract_sale_detail.html
{% extends "layout.html" %}

{% block body %}
    
  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8 p-3 mb-2 bg-light text-dark">

        <!-- Contract Alias -->
        <h4 class="mt-4">Contract Sales Detail</h4>
        <hr>
        <!-- Post Content -->
        <p class="lead">
            <b>Contract Alias:</b> {{ contract_sale.contract__contract_alias|safe }}
        </p>
        <p class="lead">
            <b>Date:</b> {{ contract_sale.date|safe }}
        </p>
        {% for key, value in contract_sale.sales_data.items %}
        <p class="lead">
            <b>{{key}}:</b> {{ value|safe }}
        </p>
        {% endfor %}
        <p class="lead">
            <b>Rate Amount:</b> {{ contract_sale.contract__rate_amount|safe }}
        </p>
        <p class="lead">
            <b>Total Amount:</b> {{ contract_sale.total_amount|safe }}
        </p>
        <p class="lead">
            <b>Currency:</b> {{ contract_sale.contract__currency|safe }}
        </p>

        <p class="lead">
            <b>Note:</b> {{ contract_sale.note|safe }}
        </p>


    </div> <!--post content form-->
    
  </div>  <!-- /.row -->

        <a href="{% url 'accounting:contract_sales' %}">Return</a>
{% endblock body %}

templates/accounting/contract_sale/contract_sale_update.html
{% extends "layout.html" %}
contract_sale_update.html
{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
    <div class="col-md-6 offset-md-3" style = "margin-top:20px;">
        <h3>Update Contract</h3>
        <hr>
        <form method = "POST">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>

    </div>
    </div>
{% endblock body %}

templates/accounting/contract_sale/contractsales.html
{% extends "layout.html" %}
{% load humanize %}
{% load mathfilters %}
{% block body %}

    <div class="container-fluid">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <form>
                  <h3>Contract Sales</h3>
                  <p>&nbsp;</p>
<!--                  <a class="btn btn-info" href ="{% url 'accounting:add_contract_sale' %}">Add Contract Sale</a>-->
                  <a class="btn btn-primary text-gray disabled" id="id_btn_invoice" onclick="getSelectedSales('cbSales')">Make Invoice</a>
<!--                {% csrf_token %}-->
<!--                <button class="btn btn-secondary" type="submit">Search</button>-->
          </div>
<!--                <input type="text" name="keyword" class="form-control" placeholder="Input a keyword to search for ..." aria-label="" aria-describedby="basic-addon1">-->
              </form>
        </div>

        <div class="input-group mb-3">
              <div class="input-group-prepend">
                  <form>
                    {% csrf_token %}
                    <button class="btn btn-secondary" type="submit">Search</button>
              </div>
                  <input type="text" name="keyword" class="form-control" placeholder="Input a keyword ..." aria-label="" aria-describedby="basic-addon1">
                </form>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="cb-filter-data" value=0/>
            <label class="form-check-label" for="cb-filter-data">Show all sales</label>
        </div>



    {% if not contract_sales %}
        <div class="alert alert-danger" style = "margin-top:20px;">There is no contract sale yet.</div>

    {% else %}
        <table class="table table-hover" style="margin-top:20px;">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Invoice</th>
                    <th scope="col">Contract Alias</th>
                    <th scope="col">Date</th>
                    <th scope="col">Total Amount</th>
                    <th scope="col">Rate Amount</th>
                    <th scope="col">Currency</th>
                </tr>
            </thead>
            <tbody>
                {% for cs in contract_sales  %}
                    <tr>
                        <th scope="row">{{ cs.id }}</th>
                        {% if cs.is_invoiced %}
<!--                        <td><input class="form-check-input radioSales" style="vertical-align: middle; margin: 10px;" name="radio-payoff" type="radio" value="{{ cs.id }}" disabled></td>-->
                        <td><input class="form-check-input cbSales" type="checkbox"  style="vertical-align: middle; margin: 10px;" value="{{ cs.id }}" disabled/></td>
                        {% else %}
<!--                        <td><input class="form-check-input radioSales" style="vertical-align: middle; margin: 10px;" name="radio-payoff" type="radio" value="{{ cs.id }}"></td>-->
                        <td><input class="form-check-input cbSales" type="checkbox" style="vertical-align: middle; margin: 10px;" value="{{ cs.id }}"/></td>
                        {% endif %}
                        <td><a href="{% url 'accounting:contractsale-detail' cs.id %}">{{ cs.contract__contract_alias }}</a></td>
                                    <!--/articles/article/{{ article.id }}-->
                        <td>{{ cs.date }}</td>
                        <td>{{ cs.total_amount }}</td>
                        <td>{{ cs.contract__rate_amount }}</td>
                        <td>{{ cs.contract__currency }}</td>
                        <td><a href="{% url 'accounting:update_contract_sale' cs.id %}">Update</a></td>
                        <td><a class="confirm-delete" href="{% url 'accounting:delete_contract_sale' cs.id %}">Delete</a></td>
                    </tr>
                {% endfor %}

            </tbody>
            </div>
        </table>



    <script>

    let sales_ids = [];

    $(document).on('click', '.confirm-delete', function(){
        return confirm('Are you sure you want to delete this?');
    })

    function setDataFilter() {
        var is_filter = document.getElementById("cb-filter-data").value;
        if (this.checked){
            this.value = 1;
        }else{
            this.value = 0;
        }

        // send a ajax request to filter the data
        console.log("is_filter: " + this.value);
        filterData(this.value);
    }

    $(document).on('click', '#cb-filter-data', setDataFilter);

    function filterData(filter_option){
        console.log("setting invoice_data!");
        const url = "{% url 'accounting:contractsales-list' %}";
        var auth_headers = {
            Authorization: 'Token ' + 'b83aec1ffbced8ffb02a7fd6f67870df4494933d',
        }
        console.log("url: " + url);
        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/accounting/set_invoice_data/)
          method: "GET",
          //dataType: "json",
          //headers: auth_headers,
          data: {
            'is_invoiced': filter_option,       // add the contract id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_contracts` view function
            console.log("olaaaa!");
            console.log(data);
          },
            error: function(e)
            {
                console.log('Error status : ' + e.status + ', status text: ' + e.statusText);
            }
        });
    }

    function getElement(elm){
        return document.getElementById(elm);
    }

    function removeClass(elm, class_name){
        var stat = elm.classList.contains(class_name);
        if (stat == true) {
            elm.classList.remove(class_name);
            console.log("class name removed:" + class_name);
        }
    }

    function addClass(elm, class_name){
        var stat = elm.classList.contains(class_name);
        if (stat == false) {
            elm.classList.add(class_name);
            console.log("class name removed:" + class_name);
        }
    }



    function uncheckCheckboxes(className) {
        const checkboxes = document.querySelectorAll(`.${className}`);
        checkboxes.forEach((checkbox) => {
          checkbox.checked = false;
        });
    }

  // Attach the event listener to the 'beforeunload' event
  window.onbeforeunload = function () {
    // Here, you can call the function to uncheck the checkboxes with the desired class name
    uncheckCheckboxes("cbSales");
  };

    var matches = document.querySelectorAll('.cbSales');
    for (match in matches) {
      matches[match].onclick = function() {
        if (this.checked){
            console.log("checked!");
            sales_ids.push(this.value);
        }else{
            console.log("unchecked!");
            remove_from_array(sales_ids, this.value);
        }
        console.log("sales ids: " + sales_ids);
        if (sales_ids.length == 0){
            disable_btn();
        }else{
            enable_btn();
        }
      }
    }

    function remove_from_array(arr, record){
        const index = arr.indexOf(record);
        if (index > -1) { // only splice array when item is found
            arr.splice(index, 1); // 2nd parameter means remove one item only
            console.log("array: " + arr);
        }
    }

    function has_unmatching_company(dict_data){
        let company_list = [];
        for (let i=0; i < dict_data.length; i++){
            company_list.push(dict_data[i]['contract__customer__company'])
        }
        const company_set = new Set(company_list);
        company_list = Array.from(company_set);
        console.log("companies: " + company_list);
        console.log("number of company: " + company_list.length);
        console.log("allowed to proceed: " + (company_list.length === 1) );
        return company_list.length == 1;
    }

    function is_multiple_contract_selected(dict_data){
        let contract_list = [];
        for (let i=0; i < dict_data.length; i++){
            contract_list.push(dict_data[i]['contract__id'])
        }
        const contract_set = new Set(contract_list);
        contract_list = Array.from(contract_set);
        console.log("contracts: " + contract_list);
        console.log("number of contracts: " + contract_list.length);
        console.log("allowed to proceed: " + (contract_list.length === 1) );
        return contract_list.length == 1;
    }

    function set_invoice_data(){
        console.log("setting invoice_data!");
        const url = "/accounting/set_invoice_data";
        console.log("url: " + url);
        console.log("sales id: " + sales_ids);
        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/accounting/set_invoice_data/)
          dataType: "json",
          method: "POST",
          data: {
            'csrfmiddlewaretoken': '{{ csrf_token }}',
            'sales_id': JSON.stringify(sales_ids),       // add the contract id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_contracts` view function
            console.log(data);
            // check if checked sales are of different contracts
            console.log("data:" + JSON.stringify(data));
            if (is_multiple_contract_selected(data)) {
                sales_ids = []
                window.location.href = "{% url 'accounting:add_cont_sale_invoice' %}"
            }else{
                alert("you cannot invoice for multiple customers at a time!");
            }
           //
    <!--        $("#id_rate_amount").html(data.rate_amount);-->
    <!--        $("#id_rate_amount").val(data.rate_amount);-->
          },
            error: function(e)
            {
                console.log('Error: ' + e);
                sales_ids = [];
            }
        });
    }
    function getSelectedSales(cbClassName) {
      var checkboxes = document.getElementsByClassName(cbClassName);
      var checkboxesChecked = [];
      for (var i=0; i < checkboxes.length; i++) {
         if (checkboxes[i].checked) {
            checkboxesChecked.push(checkboxes[i].value);
         }
      }
      console.log("checked boxes: " +checkboxesChecked);
      // console.log("type of checked boxes: " + typeof(checkboxesChecked));
      set_invoice_data();
      return checkboxesChecked.length > 0 ? checkboxesChecked : null;
    }

    function enable_btn(){
        var btn_invoice = getElement('id_btn_invoice');
        removeClass(id_btn_invoice, "disabled");
        removeClass(id_btn_invoice, "text-gray");
        addClass(id_btn_invoice, "text-white");
    }

    function disable_btn(){
        var btn_invoice = getElement('id_btn_invoice');
        addClass(id_btn_invoice, "disabled");
        addClass(id_btn_invoice, "text-gray");
        removeClass(id_btn_invoice, "text-white");
    }

    </script>
    {% endif %}
    {% endblock body %}